// Country name to ISO 3166-1 alpha-2 code mapping
const countryNameToCode = {
  // Major countries
  'UNITED STATES': 'US',
  'USA': 'US',
  'AMERICA': 'US',
  'UNITED STATES OF AMERICA': 'US',
  'UNITED KINGDOM': 'GB',
  'UK': 'GB',
  'GREAT BRITAIN': 'GB',
  'ENGLAND': 'GB',
  'BRITAIN': 'GB',
  'CANADA': 'CA',
  'FRANCE': 'FR',
  'GERMANY': 'DE',
  'ITALY': 'IT',
  'SPAIN': 'ES',
  'AUSTRALIA': 'AU',
  'NEW ZEALAND': 'NZ',
  'JAPAN': 'JP',
  'CHINA': 'CN',
  'INDIA': 'IN',
  'BRAZIL': 'BR',
  'MEXICO': 'MX',
  'RUSSIA': 'RU',
  'SOUTH AFRICA': 'ZA',
  'ARGENTINA': 'AR',
  'CHILE': 'CL',
  'COLOMBIA': 'CO',
  'PERU': 'PE',
  'VENEZUELA': 'VE',
  'ECUADOR': 'EC',
  'BOLIVIA': 'BO',
  'PARAGUAY': 'PY',
  'URUGUAY': 'UY',
  'GUYANA': 'GY',
  'SURINAME': 'SR',
  'NETHERLANDS': 'NL',
  'BELGIUM': 'BE',
  'SWITZERLAND': 'CH',
  'AUSTRIA': 'AT',
  'PORTUGAL': 'PT',
  'SWEDEN': 'SE',
  'NORWAY': 'NO',
  'DENMARK': 'DK',
  'FINLAND': 'FI',
  'ICELAND': 'IS',
  'IRELAND': 'IE',
  'POLAND': 'PL',
  'CZECH REPUBLIC': 'CZ',
  'SLOVAKIA': 'SK',
  'HUNGARY': 'HU',
  'ROMANIA': 'RO',
  'BULGARIA': 'BG',
  'CROATIA': 'HR',
  'SLOVENIA': 'SI',
  'SERBIA': 'RS',
  'BOSNIA AND HERZEGOVINA': 'BA',
  'MONTENEGRO': 'ME',
  'ALBANIA': 'AL',
  'MACEDONIA': 'MK',
  'GREECE': 'GR',
  'TURKEY': 'TR',
  'CYPRUS': 'CY',
  'MALTA': 'MT',
  'LUXEMBOURG': 'LU',
  'ESTONIA': 'EE',
  'LATVIA': 'LV',
  'LITHUANIA': 'LT',
  'UKRAINE': 'UA',
  'BELARUS': 'BY',
  'MOLDOVA': 'MD',
  'GEORGIA': 'GE',
  'ARMENIA': 'AM',
  'AZERBAIJAN': 'AZ',
  'KAZAKHSTAN': 'KZ',
  'UZBEKISTAN': 'UZ',
  'TURKMENISTAN': 'TM',
  'KYRGYZSTAN': 'KG',
  'TAJIKISTAN': 'TJ',
  'AFGHANISTAN': 'AF',
  'PAKISTAN': 'PK',
  'BANGLADESH': 'BD',
  'SRI LANKA': 'LK',
  'NEPAL': 'NP',
  'BHUTAN': 'BT',
  'MALDIVES': 'MV',
  'MYANMAR': 'MM',
  'THAILAND': 'TH',
  'LAOS': 'LA',
  'VIETNAM': 'VN',
  'CAMBODIA': 'KH',
  'MALAYSIA': 'MY',
  'SINGAPORE': 'SG',
  'INDONESIA': 'ID',
  'PHILIPPINES': 'PH',
  'BRUNEI': 'BN',
  'TIMOR-LESTE': 'TL',
  'SOUTH KOREA': 'KR',
  'NORTH KOREA': 'KP',
  'MONGOLIA': 'MN',
  'TAIWAN': 'TW',
  'HONG KONG': 'HK',
  'MACAU': 'MO',
  'ISRAEL': 'IL',
  'PALESTINE': 'PS',
  'JORDAN': 'JO',
  'LEBANON': 'LB',
  'SYRIA': 'SY',
  'IRAQ': 'IQ',
  'IRAN': 'IR',
  'KUWAIT': 'KW',
  'SAUDI ARABIA': 'SA',
  'BAHRAIN': 'BH',
  'QATAR': 'QA',
  'UAE': 'AE',
  'UNITED ARAB EMIRATES': 'AE',
  'OMAN': 'OM',
  'YEMEN': 'YE',
  'EGYPT': 'EG',
  'LIBYA': 'LY',
  'TUNISIA': 'TN',
  'ALGERIA': 'DZ',
  'MOROCCO': 'MA',
  'SUDAN': 'SD',
  'SOUTH SUDAN': 'SS',
  'ETHIOPIA': 'ET',
  'ERITREA': 'ER',
  'DJIBOUTI': 'DJ',
  'SOMALIA': 'SO',
  'KENYA': 'KE',
  'UGANDA': 'UG',
  'TANZANIA': 'TZ',
  'RWANDA': 'RW',
  'BURUNDI': 'BI',
  'DEMOCRATIC REPUBLIC OF THE CONGO': 'CD',
  'CONGO': 'CG',
  'CENTRAL AFRICAN REPUBLIC': 'CF',
  'CHAD': 'TD',
  'CAMEROON': 'CM',
  'EQUATORIAL GUINEA': 'GQ',
  'GABON': 'GA',
  'SAO TOME AND PRINCIPE': 'ST',
  'NIGERIA': 'NG',
  'NIGER': 'NE',
  'MALI': 'ML',
  'BURKINA FASO': 'BF',
  'SENEGAL': 'SN',
  'GAMBIA': 'GM',
  'GUINEA-BISSAU': 'GW',
  'GUINEA': 'GN',
  'SIERRA LEONE': 'SL',
  'LIBERIA': 'LR',
  'IVORY COAST': 'CI',
  'GHANA': 'GH',
  'TOGO': 'TG',
  'BENIN': 'BJ',
  'MAURITANIA': 'MR',
  'WESTERN SAHARA': 'EH',
  'CAPE VERDE': 'CV',
  'MADAGASCAR': 'MG',
  'MAURITIUS': 'MU',
  'SEYCHELLES': 'SC',
  'COMOROS': 'KM',
  'MAYOTTE': 'YT',
  'REUNION': 'RE',
  'BOTSWANA': 'BW',
  'NAMIBIA': 'NA',
  'ZAMBIA': 'ZM',
  'ZIMBABWE': 'ZW',
  'MALAWI': 'MW',
  'MOZAMBIQUE': 'MZ',
  'SWAZILAND': 'SZ',
  'LESOTHO': 'LS',
  'ANGOLA': 'AO',
};

const validateCountry = countryInput => {
  // Validate and format country code - ensure it's a valid ISO 3166-1 alpha-2 code
  let validatedCountry = 'US'; // Default fallback

  if (countryInput && typeof countryInput === 'string') {
    const cleanInput = countryInput.trim().toUpperCase();

    // First, check if it's already a valid 2-letter ISO code
    if (cleanInput.length === 2 && /^[A-Z]{2}$/.test(cleanInput)) {
      validatedCountry = cleanInput;
    } else if (countryNameToCode[cleanInput]) {
      // Then, try to convert country name to ISO code
      validatedCountry = countryNameToCode[cleanInput];
    } else {
      // If it looks like a partial match, try to find it
      const matchedEntry = Object.entries(countryNameToCode).find(([name]) =>
        name.includes(cleanInput) || cleanInput.includes(name));
      if (matchedEntry) {
        const [, countryCode] = matchedEntry;
        validatedCountry = countryCode;
      }
    }
  }
  return validatedCountry;
};

module.exports = {
  validateCountry,
};
